language: node_js
node_js:
  - 8
script:
  - npm test
  - npm run lint
  - npm run typecheck
  - npm run format:check
before_deploy:
  - npm run build
deploy:
  provider: surge
  project: ./dist
  domain: https://reactquickstart.surge.sh
  skip_cleanup: true
cache:
  directories:
    - "node_modules"
